### ISSUE TITLE
As a user with a disability, I would like to have a fully 508 compliant experience.

### ISSUE THREAD

**Issue by oghaffari** [18F/dol-whd-14c#163]

**Comment by mgwalker** [comment]
I'd suggest changing this story text to something more like:

> As a user with a disability, I would like to have a fully accessible experience.

We don't want to get hung up on the language "508 compliance" because there's technically no such thing, and we'd really prefer WCAG 2.0 AA adherence (which supersets 508, and the 508 standards will soon point to WCAG directly).

The main thing, however, is that the application needs to be accessible.  We can do automated scanning of accessibility best-practices, but errors/warnings will need to be evaluated on a case-by-case basis.  Sometimes it's okay to leave elements as non-accessible because they aren't an interactive part of the app, but the automated tools don't know that.

**Comment by mmurthydol** [comment]
@mgwalker Greg, DOL actually has specific 508 compliance guidelines without which app can't go to production. Looks like #198 captures DOL guidelines.  This story #163 and #198 need to be merged :)

**Comment by mmurthydol** [comment]
Angular App controls must be developed using ARIA related attributes specific to the Angular version (AngularJS = Angular 1.x seems to use ngAria, Angular 2 has aria-). 

Current implementation doesn't seem to have any ARIA related attributes in code (save literally in 2 places).

**Comment by mmurthydol** [comment]
@oghaffari Please close this story. Not sure why I don't have permissions to do so. Story #198 supersedes this story. Thanks.

**Comment by oghaffari** [comment]
Thanks, @mgwalker! @mmurthydol, let's work on your account tomorrow and see if we can fix that.
