### ISSUE TITLE
Performance: FileRepository methods can raise OutOfMemoryExceptions

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#353]
Current implementation of methods below can raise OutOfMemoryException due to using 
public void Upload(MemoryStream memoryStream, string fileName)
{
...
memoryStream.WriteTo(fileStream)
...
}
public MemoryStream Download(MemoryStream memoryStream, string fileName)
{
...
memoryStream.WriteTo(fileStream) & fileSteam.CopyTo(memoryStream);
...
}

## Acceptance Criteria
- [ ] Methods above will implement byte[] based implementation that mitigates/eliminates OutOfMemoryException issues.

#### Functionality

- [ ] Update this method public void Upload(MemoryStream memoryStream, string fileName)
       to not use memoryStream.WriteTo(fileStream) but use WriteAsync(byte[]). TODO Think through 
       whether we need CancellationToken overload.
- [ ] Update this method public MemoryStream Download(MemoryStream memoryStream, string fileName)
      to not use fileSteam.CopyTo(memoryStream);
      but to use fileSteam.CopyToAsync(memoryStream, bufferSize) overload
- [ ] Create a new overloaded method public void Upload(bytes[] bytes, string fileName)
       that will read byte chunks in a for loop. One Upload method should be able to be written with 
       respect to another overload above. 
- [ ] Create a new public MemoryStream Download(MemoryStream outStream, byte[] bytes) 
        that will work with byte chunks in a for loop. One Download method should be able to be written 
        with respect to another overload above. 
    
Note to DOL: links below for reference.    -
 [ ] https://stackoverflow.com/questions/2809514/outofmemoryexception-when-i-read-500mb-filestream
- [ ] https://msdn.microsoft.com/en-us/library/system.io.memorystream_methods(v=vs.110).aspx

#### Accessibility
N/A
##### Keyboard Accessibility
N/A

**Comment by mgwalker** [comment]
@mmurthydol If this risk is unacceptable to WHD, then it should be fixed in #324.  I'm not comfortable "accepting" known-defective code.  Bear in mind that the risk is partially mitigated by the IIS configuration that doesn't accept HTTP request bodies over a certain size and WHD can configure that to whatever they want.

**Comment by mmurthydol** [comment]
@mgwalker I created #353 for this defect. I'd prefer that we merge the code so as to not block Harun/UX team from their work. #353  is prioritized high enough that it will be fixed in the upcoming sprint as in the next day or two. Thanks!

**Comment by suprenant** [comment]
@mgwalker is right that we should avoid merging code with known defects. Merging problematic code and writing new issues for bugs is an antipattern that will cause us trouble; there may even be contractual issues with our doing this. 

Broadly, I would suggest that we adopt "code does not have any known bugs or defects" in our Definition of Done and that we adhere to that so we know our code is solid and that we're not making problems for ourselves in the future. 

Specifically, if this issue is blocking other work, let's flag that work as blocked and then swarm to fix the blocking issue so the other work can proceed. 

If it makes sense for us to meet, talk through our tech standards and process, and make sure we're all aligned, let's do that once Greg is back in the office on Wednesday.

**Comment by suprenant** [comment]
From our post-standup conversation (via Jason), @dciceman is working on this item now and expects to finish the work today so we can be unblocked here. 

For next time, Greg and I can talk about ways to help work continue (e.g. possibly creating separate branches) as well as the range of possible defects we might face and which should block us and which, if any, we would be comfortable triaging for later. Thanks to @mmurthydol @jmmcnj for flagging and helping us work through this together.

**Comment by mmurthydol** [comment]
Thanks @suprenant

**Comment by mmurthydol** [comment]
@dciceman David, I believe this has been done for a while. I am closing it. Please reopen if you think otherwise.
