### ISSUE TITLE
Implementation - As a WHD Security Officer, I would like each User's session to timeout from inactivity set to WHD policies

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#464]
For reference, please use: #76 

Please use the most recent prototype link (latest comment from Shannon in story #76): https://preview.uxpin.com/6dc6e8912fdaeb32cdfefa6e237f0d300d960588#/pages/77031627/simulate/no-panels?mode=i

- [x] Research spike on Angular Module - https://hackedbychinese.github.io/ng-idle/ 
- [x] Implement module 
- [ ] Test - Regression tests/code cov/Accessibility Testing

**Comment by mmurthydol** [comment]
@mgwalker Greg this is a security story on the UI side only if you think you can take a crack at it. Thanks!

**Comment by mgwalker** [comment]
This comment is mostly for myself, so I don't lose it. [This ng-idle angular module](https://hackedbychinese.github.io/ng-idle/) looks like it'll get us most of the way there.

**Comment by mmurthydol** [comment]
@davoodharun please ensure the latest UXPIN from Shannon comment is being used (believe so). If you assign this story to Steven, please oversee implementation. Security story - critical for ATO. Thanks.

**Comment by jmmcnj** [comment]
Parameters from Policy/discussion:
Warning at 13 minutes
Lockout at 15 minutes

**Comment by binwang89** [comment]
For system timeout, below conditions will cause the accessibility not compliant :
 
1. The application timed out without notification
2. The application's time out notification is displayed for less than 20 seconds
3. The application timed out without an option to request more time

**Comment by binwang89** [comment]
@mmurthydol @EStriegel tested in QA site and please see below screenshot,  

![image](https://user-images.githubusercontent.com/25330625/36220297-0fd09d72-1188-11e8-9c8c-8db5d0414890.png)

Also checked the parameters setting in source code (app.js):

app.config(function(IdleProvider, KeepaliveProvider) {
--
  | // configure Idle settings
  | IdleProvider.idle(780); // in seconds
  | IdleProvider.timeout(120); // in seconds
  | IdleProvider.autoResume(false);
  | KeepaliveProvider.interval(2); // in seconds
  | })

Since we still have UI style needs to be fixed(only pending item now),  I will move this user story to "IN Progress".
