### ISSUE TITLE
Bug: Accessibility: 508: Employee Data Table - Keyboard Focus (Delete and Back buttons)

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#535]
> Note: This requires Data Tables / Angular work

Work Sites & Employees Page
https://dol-whd-section14c-int.aisdemos.com/#!/section/work-sites

**Keyboard Accessibility Bug:**
In the Employee data table, keyboard focus is lost after the last "Delete" button and before the "Back" button. (when tabbing)

**Comment by binwang89** [comment]
@davoodharun Harun, please provide the estimate for this issue. Thanks

**Comment by mmurthydol** [comment]
Harun mentioned this is not a simple fix.

**Comment by NathayaMDOL** [comment]
The keyboard focus is lost after the last "Delete" button and before the "Back" button because of the tabbing is focusing on "Previous" button which is disabled.  
After I investigated to the issue. The good solution for this one has little change on UI as screenshot below. Instead of disabled the “button (previous/next)”, UI has been changed to not showing the “Previous button” if at 1st page and not showing “Next button” if at last page.
Branch: "whd-aqa-535-nmankong-508-datatable-keyboardfocus-ondisabledbtn"
![previoius](https://user-images.githubusercontent.com/40499717/44060408-9b668e50-9f22-11e8-882a-e43e2a4c0885.PNG)
![middle](https://user-images.githubusercontent.com/40499717/44060414-9f5121ba-9f22-11e8-8b3c-e5ede1f7c520.jpg)
![next](https://user-images.githubusercontent.com/40499717/44060417-a13666de-9f22-11e8-9e8c-a65e52105d05.PNG)

**Comment by binwang89** [comment]
@NathayaMDOL it looks fine.

**Comment by binwang89** [comment]
@NathayaMDOL it seems working good in Google Chrome, however, it is not working for IE. as we discussed, please make sure the IE will get the same result.  The tabbing is not working for data table in this page in IE.

**Comment by binwang89** [comment]
move it to done.
