### ISSUE TITLE
Bug: Register Employer - Clicking the hyperlink, "What if the Employer's legal name changed since its last application?" should also open instruction.  Same functionality as clicking blue question mark.  Should review if there is any other similar styling throughout app.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#599]
Bug description:
In Chrome, Register Employer - Clicking the hyperlink, "What if the Employer's legal name changed since its last application?" should also open instruction.  Same functionality as clicking blue question mark.  Should review if there is any other similar styling throughout app.
@EStriegel please provide the screenshot or information related to this issue found in QA.

**Comment by ltsheu** [comment]
@binwang89 This bug is probably best remediated with Angular since it is a click interaction. Thanks.

**Comment by mmurthydol** [comment]
@NathayaMDOL Please reproduce this defect and provide screenshots to Liz for next steps.

**Comment by NathayaMDOL** [comment]
@EStriegel and @mmurthydol ,
The defect has been reproduced and below is the screenshot on Register Employer page.
When clicking the hyperlink, "What if the Employer's legal name changed since its last application?". The instruction message box should open.
![registeremployerpagedefect](https://user-images.githubusercontent.com/40499717/42590342-913dfb3c-8511-11e8-8909-59498db5b23d.png)

Thanks,
Nathaya

**Comment by NathayaMDOL** [comment]
The hyperlink defect has been fixed and pushed to branch “whd-aqa-599-nmankong-register-employer-clicking-hyperlink”

**Comment by EStriegel** [comment]
Confirmed complete during demo on 7/18
