### ISSUE TITLE
Bug: Email is not always firing on application submission

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#603]
- [ ] @binwang89 Verify emails are being sent / whether error logs show email failure

Sometimes happens, need to find pattern

**Comment by jmmcnj** [comment]
Madhu - further research needed to see pattern of failures if any, otherwise deeper bug review to find problems

**Comment by EStriegel** [comment]
@binwang89 Can you review the error logs to see if there is a pattern for email failures?

**Comment by binwang89** [comment]
@EStriegel @mmurthydol I have tested. However, I can't submit the application.  
2 issues i found when testing the 14c. 
1. The Worksite/Employee page can't show previous work site  and I can't correct the the error. 
2. while in the middle of working on the application, the system timeout message popup and asked me if i need more time.

**Comment by binwang89** [comment]
@EStriegel @mmurthydol @PrabhakarThummalaDOL after i retested today (log off and log back in to 14c),  it seems the issue was not there.  I think it maybe browser  or API refresh issue. I can not reproduce the same error anymore. 

![image](https://user-images.githubusercontent.com/25330625/37542632-324d59ca-2935-11e8-945f-c3ce44c28bfe.png)

**Comment by EStriegel** [comment]
Cannot reproduce.  Moving to `Closed`

**Comment by mmurthydol** [comment]
@binwang89 @EStriegel Michelle/Liz: Problem must have resolved from 14c online sending emails to the logged in user instead of contact person email

**Comment by binwang89** [comment]
@EStriegel @mmurthydol I have tested the application and this issue has been resolved.  I will close it.
