### ISSUE TITLE
As an applicant, I would like a landing page after log-in so that I can begin a new application or continue to work on an application in progress so that I can easily navigate the application.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#70]
Other functions for the landing page could include - ability to view application status, access current certificates and view previous submissions.

**Comment by jmmcnj** [comment]
@EStriegel We completed what had been stated in the User Story title but have not added, the "other functions" identified in your comment Oct 21 above.  It is up to you if you would like to create a separate user story for the "other functions" or further define this user story to include those functions and leave the User STory in Progress.  We may need to collaborate on this one

**Comment by jmmcnj** [comment]
Descripition: Creation of a landing page after login for Applicants that either allows them to start a new application or continue an existing application that they have saved in "draft" status.  This landing page will be different for Administrators, instead of showing the application button they will see something different, this will be defined in the Administration section User Stories


Tasks:
- [ ] Create landing page view
- [ ] Create button that toggles between start or continue 14c application depending upon what state Applicant is in with their application
- [ ] If user is not the role of Applicant they will not see the button at all, but will see administration section, what they see in Admin section will be depend on their administrative role

Acceptance Criteria:  User logs in successfully to the application and if they are of the role Applicant they will be taken to a page with a button to start an application if this is their first time/existing certified applicant going in for renewal or continue an application if they show an existing draft status application in the system.
Considerations:
1. Application Status: Initial or Draft
2. Role: Applicant

**Comment by jmmcnj** [comment]
We are going to split off the "other functions" described in the first comment thread into a new User Story

**Comment by mgwalker** [comment]
@jmmcnj Can you make the `greg.walker@gsa.gov` account an admin so I can check look at these things?  I will create a new account for checking non-admin stuff.  Thanks!

**Comment by jmmcnj** [comment]
@mgwalker done, I set your greg.walker@gsa.gov account as system admin
