### ISSUE TITLE
Security: Disabled users must do what to login in to the system?

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#708]
@EStriegel Liz, let's talk about this. What should happen from your perspective?

**Comment by EStriegel** [comment]
@mmurthydol 

Process for disabled account to be reactivated: 
- User attempts to log-in by entering user name/password
- If account has been disabled, user sees screen that says, "Due to account inactivity, your account has been disabled.  An email has been sent to you with a link to reset your password.  You must click this link, and change your password, to reactive your account."
- System sends email with link to reset password.
- Link takes user to reset password page.
- Once new password is saved, account is reactived.
- User is able to log-in by entering user name/password.


**Note:** I updated the story title to say "Disabled users" instead of "Deleted users"

**Comment by EStriegel** [comment]
Implementation story #707.  Closed.
