### ISSUE TITLE
Bug: UI - Validate column length for CITY and STREET_ADDRESS1 columns.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#762]
- [x] UI - Restrict user entering more than the size of the column for Addresses columns (City and Street_Address1).

**Comment by NathayaMDOL** [comment]
This issue has been fixed by using maxlength to specifies the maximum number of characters allowed in the input element. 
Branch: "whd-aqa-762-nmankong-maxlength-streetaddress1-city"
![maxlength-city-street1](https://user-images.githubusercontent.com/40499717/43416012-1d2c2ca2-9405-11e8-95e6-d15670bc47e1.png)

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
