### ISSUE TITLE
Security: Send email to the deactivated users.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#777]
On application start:
- [x] Send an email to all the deactivated users. (email text, email subject - configurable)
- [x] On every email failure, log the error.
- [x] Avoid sending duplicate emails to the deactivated user. (can occur from servers on web farm). Check the database if the column (disabled) was already updated recently on the same day, prior to sending the email.

@EStriegel Need email verbiage.
ERS Comment: Email verbiage added in comment below.

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL 

_Subject Line_ 
Disabled Account: Department of Labor Section 14(c) Online Certificate Application

_Email Body_
Your account with the Department of Labor Section 14(c) Online Certification Application has been disabled due to inactivity.  

There is no action required at this time.  However, the next time you attempt to log-in to your account, you will be asked to reset your password before accessing your account.

Thank you.

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
