### ISSUE TITLE
Update the Banner page verbiage

### ISSUE THREAD

**Issue by NathayaMDOL** [18F/dol-whd-14c#833]
Update the Banner page. From Lliz'email, this should be sufficient.
“Please do not upload Personal Identifying Information (PII) about a section 14(c) certificate holder or any employees to the Section 14(c) Online Application. PII refers to information which can be used to distinguish or trace an individual's identity, such as their name, social security number, biometric records, etc. alone, or when combined with other personal or identifying information which is linked or linkable to a specific individual, such as date and place of birth, mother's maiden name, etc.”

**Comment by NathayaMDOL** [comment]
Banner page verbiage has been updated.
![image](https://user-images.githubusercontent.com/40499717/48021742-514fb900-e107-11e8-911d-6803f33a2501.png)
Branch: "whd-aqa-833-nmankong-update-bannerpage-verbiage"

**Comment by EStriegel** [comment]
@NathayaMDOL Please update so that the following is included on the banner page:

-------
You are accessing a U.S. Government information system that is owned and operated by the Department of Labor. There is no expectation of privacy when accessing this system. The Department of Labor information systems are provided for the processing of official U.S. Government information only, and are therefore, owned by the Department of Labor. Authorized users are responsible for the proper handling of the Government data equipment and resources which they access. Use of this system by any user authorized or unauthorized constitutes a consent to this monitoring, recording, disclosure, and accepts that use of the system is subject to audit by authorized personnel. Fraud and related activity in connection with computers is prohibited by Title 18, U.S. Code Section 1030. Furthermore, this law states that intentionally accessing a computer without authorization or exceeding authorized access and thereby obtaining information from any department or agency of the United States is prohibited and subject to civil and criminal penalties, including (but not limited to), punishment by fine and/or imprisonment. Additionally, DOL may provide law enforcement with any potential evidence of a crime found on aforementioned systems in order for them to investigate such offenses.

Please do not upload Personal Identifying Information (PII) about a section 14(c) certificate holder or any employees to the Section 14(c) Online Application. PII refers to information which can be used to distinguish or trace an individual's identity, such as their name, social security number, biometric records, etc. alone, or when combined with other personal or identifying information which is linked or linkable to a specific individual, such as date and place of birth, mother's maiden name, etc.

**Comment by NathayaMDOL** [comment]
![image](https://user-images.githubusercontent.com/40499717/49048144-c3b43600-f1a7-11e8-9831-17f0337e59a5.png)

**Comment by EStriegel** [comment]
Looks good!  Complete.
