### ISSUE TITLE
Implement all the OPA Text Edits

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#860]
Liz, please let me/us know which edits are missing/off. Thanks!

**Comment by EStriegel** [comment]
@mmurthydol Edits still needed: (I don't know what I did to make the formatting so wonky)
----
YOUR ACCOUNT PAGE
https://section14cdev.dol.gov/#!/youraccount

Page should have an <h2> with the text of “Your Account”

----
EMPLOYER SECTION
https://section14c.dol.gov/#!/section/employer

Update the validation error messages for the Zip Code field for physical address and parent organization address (must answer yes to "Does the Employer have a Parent Organization" to trigger validation error message).

From: Please provide a valid zip code for the employer's main establishment
To: Please provide a valid Zip Code for the employer's main establishment

----
DEV REVIEW & SUBMIT SECTION
https://section14cdev.dol.gov/#!/section/review

Make the following grammatical edit (Edits were made, but **there is an extra comma between Avenue and NW that needs to be deleted**)

From: Send comments regarding the burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to the Administrator, Wage and Hour Division, U.S. Department of Labor, Room S-3502, 200 Constitution Avenue, N.W., Washington, DC 20210 and reference the OMB Control Number.

To: Send comments regarding the burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to the Administrator, Wage and Hour Division, U.S. Department of Labor, Room S-3502, 200 Constitution Ave NW, Washington, DC 20210, and reference the OMB Control Number.

----
PASSWORD RESET EMAIL MESSAGE
Can we make these copy edits to the subject of the email?
From: Reset Password
To: Reset Password: U.S. Department of Labor's Section 14(c) Online Certificate Application

Can we make these copy edits in the body of the email?
From: Password Reset Link:
To: To reset your password please click this link, or copy and paste it into your browser:

-----
RESET PASSWORD PAGE
Can we make these copy edits to the Password Reset confirmation message?
From:
Password Reset
Your password has been reset. Please Login with your new password.
To:
Password Reset
Your password has been reset. Please log in with your new password.

-----
CONFIRMATION EMAIL MESSAGE
Can we make these copy edits in the subject of the email?
From: Confirm your account for the Department of Labor Section 14(c) Online Certificate Application
To: Confirm Your Account: U.S. Department of Labor's Section 14(c) Online Certificate Application

-----
AUTHENTICATION CODE EMAIL MESSAGE
Can we make these copy edits to the subject of the email?
From: Authentication Code: Department of Labor Section 14(c) Online Certificate Application
To: Authentication Code: U.S. Department of Labor's Section 14(c) Online Certificate Application
----
REGISTER AN EMPLOYER PAGE
https://section14c.dol.gov/#!/employerRegistration

Can we make "Register an Employer" an h2 instead of an h3? (Same size as the online certificate application header)

Can we remove the horizontal rule after "Register an Employer "? (there's too much empty space between the online application header and the register an employer header)

**Comment by EStriegel** [comment]
Unable to confirm edits on the following pages because I am out of email addresses to create a new account: 
-----
AFTER CLICKING THE ACCOUNT CONFIRMATION LINK

Can we make the following copy edits?
From:
Account Confirmed!
Thank you for confirming your account. You may now log in .
To:
Account Confirmed!
Thank you for confirming your account. You may now log in.
-----
REGISTER AN EMPLOYER PAGE
https://section14c.dol.gov/#!/employerRegistration

Can we make "Register an Employer" an <h2> instead of an <h3>?

Can we remove the horizontal rule (<hr>) after "Register an Employer "?

Can we make the following copy edits?
From: If you do not have an EIN, do not enter your social security number. Please contact the Certification Team at (312)596-7195 before creating an account.
To: If you do not have an EIN, do not enter your social security number. Please contact the Certification Team at 312-596-7195 before creating an account.

Can we change the validation message for the Zip Code field to match the capitalization of the field?
From: Please provide a zip code.
To: Please provide a Zip Code.
-----
RESET PASSWORD PAGE
Can we make these copy edits to the Password Reset confirmation message?
From:
Password Reset
Your password has been reset. Please Login with your new password.
To:
Password Reset
Your password has been reset. Please log in with your new password.
-----
CONFIRMATION EMAIL MESSAGE
Can we make these copy edits in the subject of the email?
From: Confirm your account for the Department of Labor Section 14(c) Online Certificate Application
To: Confirm Your Account: U.S. Department of Labor's Section 14(c) Online Certificate Application

Can we make these copy edits in the body of the email?
From: Thank you for registering for the Department of Labor Section 14( c ) Certificate Application. Please confirm your account by clicking this link or copying and pasting it into your browser:
To: Thank you for registering for the U.S. Department of Labor's Section 14(c) Certificate Application. Please confirm your account by clicking this link, or copying and pasting it into your browser:
----
AUTHENTICATION CODE EMAIL MESSAGE
Can we make these copy edits to the subject of the email?
From: Authentication Code: Department of Labor Section 14(c) Online Certificate Application
To: Authentication Code: U.S. Department of Labor's Section 14(c) Online Certificate Application

**Comment by EStriegel** [comment]
@NathayaMDOL Please make the following text edits:

1. Employer Section **CONFIRMED**
- Update the validation messages for the zip code fields (physical address and parent organization) so that Zip Code is capitalized.  Pleas ensure this edit is consistent throughout the application.


2.  Review & Submit Page **CONFIRMED**
- Within the Public Burden Statement (bottom of page), please remove the comma between Avenue and NW in the address in the last sentence.


3. Password Reset Email  **FAIL**
-  Change the subject line to, "Reset Password: U.S. Department of Labor's Section 14(c) Online Certificate Application"
- Change the body of the email to, "To reset your password please click this link, or copy and paste it into your browser: <link>"


4.  Password Reset Confirmation Message **CONFIRMED**
- Change to, 
"Password Reset
Your password has been reset.  Please log in with your new password."


5.  Confirmation Email Message **CONFIRMED**
- Change the subject line to, "Confirm Your Account: U.S. Department of Labor's Section 14(c) Online Certificate Application"


6. Authentication Code Email Message  **NO LONGER NEEDED**
- Change the subject line to, "Authentication Code: U.S. Department Of Labor's Section 14(c) Online Certificate Application" 


7. Register an Employer Page **CONFIRMED**
- Register An Employer header is too big, and there is too much space between the online application header and the register an employer header.

**Comment by EStriegel** [comment]
@NathayaMDOL @mmurthydol Have reviewed all text edits (see confirmation in comment above).  

One remaining text edit - For the password reset email, the subject line is still, "Reset Password".  Please change the subject line to, "Reset Password: U.S. Department of Labor's Section 14(c) Online Certificate Application"

**Comment by PrabhakarThummalaDOL** [comment]
Fixed. 
(Updated parameters.xml)
