### ISSUE TITLE
Bug: Employer Registration EIN "i" tool tip is not working correctly

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#861]
related to story #835. Thanks to Michelle for finding this defect.

@EStriegel please rate severity of this defect: (Critical, Major, Minor).

## Bug Description
in Employer Registration page:
1)	“i” icon is missing.
2)	The tooltip for EIN shows up as soon as the page loads. 
3)	Unrelated to the reported problem, please remove the “hyperlink” for the phone number to get around the weird focus problem. 

Desired behavior for (1) & (2) is captured in #835 which is (show the tooltip when “i” is clicked on  or tabbed to (508). If tabbed to, next tab should give focus to EIN text box, Shift+Tab should give focus back to wherever you where before focus came to “i”.

_Desired behavior_:
![image](https://user-images.githubusercontent.com/25183303/49267082-ae990a80-f426-11e8-95f5-3ea23972020a.png)

 
_Actual behavior_:
![image](https://user-images.githubusercontent.com/25183303/49267087-b5278200-f426-11e8-99e0-a221ca15d170.png)

## Acceptance Criteria

same as #835 

#### Functionality

same as #835 

##Accessibility
same as #835

**Comment by NathayaMDOL** [comment]
This issue is not a defect regarding the requirement below.
1)     Please add this under EIN in the Employer Registration Page.
If you do not have an EIN, do not enter your social security number.  Please contact the Certification Team at (312) 596 - 7195 before creating an account.
2)     In the employer tab next to EIN please add an “i” with the same verbiage as above.
3)     Approval screenshot below (#3 for the Employer Registration Page, and #1 for the Employer tab)

![3](https://user-images.githubusercontent.com/40499717/49300179-85609480-f48f-11e8-8b5a-5a5ad02fa015.jpg)
![1](https://user-images.githubusercontent.com/40499717/49300184-87c2ee80-f48f-11e8-8a2a-04abcbba0e74.jpg)

**Comment by binwang89** [comment]
@NathayaMDOL @mmurthydol i will close this item.
