### ISSUE TITLE
Error at DOL DEV environment 

### ISSUE THREAD

**Issue by michellewang89** [18F/dol-whd-14c#94]
Response error at DEV environment when Register/login
[Response error at DEV.docx](https://github.com/18F/dol-whd-14c/files/589473/Response.error.at.DEV.docx)

**Comment by jmmcnj** [comment]
Is this related to the issue of having a certificate mismatch at the api server?  This was brought up in previous discussions.  Seems like an Insecure response would be related to that.  Has DOL looked into resolving the certificate mismatch issues?

**Comment by michellewang89** [comment]
Yes, it is,  i have worked with OCIO to see if they can generate the certificate for DEV environment.  But per Patrick, they can't do it for DEV.  They only do it for Test and above environments ( Staging, Production). 
can AIS team make the required SSL a configuration option ?

**Comment by mgwalker** [comment]
Why can OCIO not generate a certificate for the dev environment?

Per Matt's previous suggestion, you should also be able to accept the certificate manually.  Open this API URL in your web browser:  https://section14cdev.dol.gov/api/Account/Register - It should tell you that you have an insecure connection.  Tell it to accept the certificate (here are [instructions for doing that in various browsers](https://support.solarwinds.com/Success_Center/Virtualization_Manager_(VMAN)/Accept_a_self-signed_certificate)).  Once you have accepted the certificate, you should be able to use the site properly for a while.

The biggest question, and correct solution, remains, though: why can't OCIO generate certificates for the dev environment?  If there are policies against it, please see if they will allow the use of a free, trusted certificate provider such as [Let's Encrypt](https://letsencrypt.org/).  It is very silly to not allow certificates _at all_ in development environments.

**Comment by jmmcnj** [comment]
This would have to go in the backlog as a User Story/Chore.  Matt recommended a work around for the meantime: "You may need to visit the api endpoint and accept the self-signed cert before it works.  I don’t recall the domain/url, but is should be similar to the web url but instead of “web”, “api”."

**Comment by michellewang89** [comment]
i just go the the API URL in chrome, but i did not see anything there 

![image](https://cloud.githubusercontent.com/assets/19672037/20269617/f1d49088-aa51-11e6-9818-a641138172c6.png)

**Comment by mgwalker** [comment]
You may need to click the red triangle with the exclamation mark, in the URL bar.  That might open up the certificate/security panel.

If OCIO can't/won't create a certificate, is there any way we can get access to the dev environment? It is difficult to be helpful when we can't see and poke around at it.

**Comment by mgwalker** [comment]
To the question of how to import the certificate into the Trusted Root Certificate Authorities list, here is a link that describes that process:  http://www.sqlservermart.com/HowTo/Windows_Import_Certificate.aspx

Sorry the earlier link didn't include those instructions!

**Comment by michellewang89** [comment]
ok, just done !
let me try it again, i hope i can test the app now in DEV

**Comment by michellewang89** [comment]
![image](https://cloud.githubusercontent.com/assets/19672037/20270942/0d17fd12-aa57-11e6-9a9e-1b6a490fd34a.png)

**Comment by mgwalker** [comment]
@jmmcnj Can we go ahead and add a chore for sprint 4 to make the SSL requirement configurable, and bump it up in priority?  It seems that OCIO isn't willing to budge on creating a certificate for the dev environment, and adding the self-signed cert to the root CA list isn't helping @michellewang89.  This really feels like a policy problem at OCIO but we can work around it fairly easily, so let's just do that.

@michellewang89 If AIS is able to get this into sprint 4, it means you won't be able to test the dev environment until sprint 4 is complete, accepted, and Patrick has deployed it.

**Comment by michellewang89** [comment]
yes, at the mean time, we just test the 14c at cloud.  once the code has been changed,  we need to test it and make sure it won't impact to anything else.

**Comment by mgwalker** [comment]
For our information going forward, DOL doesn't issue certificates to development environments due to the costs of audits and policy implementation of using certs.  Instead, they offer self-signed certificates that don't assert anything.  The certificates are managed by a 3rd-party, but that cost is not the issue here.

**Comment by rrefoy** [comment]
@michellewang89 Can you confirm whether or not this can be closed?

**Comment by mgwalker** [comment]
mgwalker [8:51 AM]  
We were able to get past the certificate issue and disable SSL.  Anyone still seeing the certificate issue may have to clear their browser cache and/or HSTS ([instructions for clearing HSTS here](http://classically.me/blogs/how-clear-hsts-settings-major-browsers)).  We were seeing another issue when we reached the end of the workday - Patrick couldn't create a new account, and the error message coming back from the API was just a generic error.

I spun up a local dev environment in a VM to see if I could replicate, and I got the same error when I did not have an email server configured, but Patrick and I haven't talked again since then so I'm not sure if the same issue could be happening in DOL or not.

**Comment by MrMatt57** [comment]
FWIW, we are using smtp4dev locally to receive/test email. https://smtp4dev.codeplex.com/

**Comment by michellewang89** [comment]
i just tested it again for registration - 
![image](https://cloud.githubusercontent.com/assets/19672037/20728733/1608fe24-b64d-11e6-95bc-e1468b3599f8.png)

**Comment by mmurthydol** [comment]
This story could be closed from a vendor perspective & archived.
